version: '{build}'

cache:
- nim-0.18.0_x64.zip -> .appveyor.yml
- x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z -> .appveyor.yml
- .cache -> .appveyor.yml
- blas.dll
- zlib1.dll

matrix:
  fast_finish: true

environment:
  matrix:
    - MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
      MINGW_DIR: mingw64
      # We need to hardcode a mirror otherwise the download fails
      MINGW_URL: https://ayera.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
      NIM_ARCHIVE: nim-0.18.0_x64.zip
      NIM_DIR: nim-0.18.0
      NIM_URL: https://nim-lang.org/download/nim-0.18.0_x64.zip
      platform: x64

install:
  - MKDIR %CD%\tools_tmp
  - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" -o"%CD%\tools_tmp"> nul
  - IF not exist "%NIM_ARCHIVE%" appveyor DownloadFile "%NIM_URL%" -FileName "%NIM_ARCHIVE%"
  - 7z x -y "%NIM_ARCHIVE%" -o"%CD%\tools_tmp"> nul
  - SET PATH=%CD%\tools_tmp\%NIM_DIR%\bin;%CD%\tools_tmp\%MINGW_DIR%\bin;%PATH%
  - IF not exist "blas.dll" (
    (nuget install OpenBLAS -o "${env:APPVEYOR_BUILD_FOLDER}") &
    (copy OpenBLAS.0.2.14.1/lib/native/bin/x64/libopenblas.dll blas.dll)
    )
  - IF not exist "zlib1.dll" (
    (nuget install zlib-msvc14-x64 -o "${env:APPVEYOR_BUILD_FOLDER}") &
    (copy zlib-msvc14-x64.1.2.11.7795/build/native/bin_release/zlib.dll zlib1.dll)
    )
  # - ps: Start-FileDownload http://icl.cs.utk.edu/lapack-for-windows/libraries/VisualStudio/3.7.0/Dynamic-MINGW/Win64/liblapack.dll lapack.dll # This does not work, why?
  - SET PATH=%PATH%;%CD%

build_script:
  - nimble.exe refresh

test_script:
  - nimble.exe test_no_lapack

deploy: off
