version: '{build}'

cache:
- nim-0.18.0_x64.zip
- x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
- packages -> **\packages.config
- '%LocalAppData%\NuGet\Cache -> **\packages.config'

matrix:
  fast_finish: true

environment:
  matrix:
    - MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
      MINGW_DIR: mingw64
      MINGW_URL: https://ayera.dl.sourceforge.net/project/mingw-w64/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
      NIM_ARCHIVE: nim-0.18.0_x64.zip
      NIM_DIR: nim-0.18.0
      NIM_URL: https://nim-lang.org/download/nim-0.18.0_x64.zip
      platform: x64

install:
  - MKDIR %CD%\tools_tmp
  - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
  - 7z x -y "%MINGW_ARCHIVE%" -o"%CD%\tools_tmp"> nul
  - IF not exist "%NIM_ARCHIVE%" appveyor DownloadFile "%NIM_URL%" -FileName "%NIM_ARCHIVE%"
  - 7z x -y "%NIM_ARCHIVE%" -o"%CD%\tools_tmp"> nul
  - SET PATH=%CD%\tools_tmp\%NIM_DIR%\bin;%CD%\tools_tmp\%MINGW_DIR%\bin;%PATH%
  - ps: nuget install OpenBLAS -o "${env:APPVEYOR_BUILD_FOLDER}"
  - ps: cp OpenBLAS.0.2.14.1/lib/native/bin/x64/libopenblas.dll blas.dll
  - SET PATH=%PATH%;%CD%

build_script:
  - nimble.exe refresh

test_script:
  - nimble.exe test

deploy: off
